In [33]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
# string = tf.Variable("This is a string", tf.string)
# number = tf.Variable(123, tf.int32)
# floating = tf.Variable(23.45, tf.float32)

In [4]:
# print(string)
# print(number)
# print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=23.45>


Rank or Degree of a tensor

In [5]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(123, tf.int64)
floating = tf.Variable(23.45, tf.float64)

In [15]:
rank1_tensor = tf.Variable(["naman","how about it"], tf.string)
rank2_tensor = tf.Variable([['1st', '2nd', '3rd'], ['1st', '2nd', '']], tf.string)


In [9]:
# tf.rank(string)
tf.rank(rank1_tensor)
# tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Shape of a tensor

In [10]:
string.shape

TensorShape([])

In [11]:
rank1_tensor.shape # one dimensonal tensor so, number of elements is shape

TensorShape([2])

In [16]:
rank2_tensor.shape # two dimensional tensor

TensorShape([2, 3])

Changing shapes

In [30]:
tensor1 = tf.ones([1,2,3], tf.int32) # one list, inside that 2 more lists, with each list containing 3 elements
tensor2 = tf.reshape(tensor1, [2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) # three lists, we have 6 elements thus it needs to be
# populated by 2 each


In [31]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]], shape=(2, 3, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


**Types of Tensors**



1.   Variable - mutable tensor
2.   Constant - immutable
3.   Placeholder - immutable
4.   SparseTensor  - immutable

